//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDD_DIALOG1                     101
#define IDB_TAB_NORMAL                  102
#define IDB_TAB_SELECTED                103
#define IDD_CFG_SIMPLE                  103
#define IDB_TAB_HILITED                 104
#define IDD_CFG_FADE                    104
#define IDD_CFG_BLT                     105
#define IDD_CFG_DOTPLANE                106
#define IDD_CFG_OSCSTAR                 107
#define IDD_CFG_NFC                     108
#define IDD_CFG_BLUR                    109
#define IDD_CFG_BSPIN                   110
#define IDD_GCFG_BEAT                   111
#define IDD_GCFG_DISP                   112
#define IDD_CFG_PARTS                   113
#define IDD_GCFG_ABOUT                  114
#define IDD_CFG_FILTER                  115
#define IDD_CFG_ROTBLT                  116
#define IDD_CFG_SVP                     117
#define IDD_CFG_COLORFADE               118
#define IDD_CFG_COLORCLIP               119
#define IDD_CFG_ROTSTAR                 120
#define IDD_CFG_OSCRING                 121
#define IDD_CFG_TRANS                   122
#define IDB_BITMAP1                     122
#define IDD_GCFG_PRESET                 123
#define IDD_CFG_SCAT                    124
#define IDD_CFG_DOTGRID                 125
#define IDD_CFG_STACK                   126
#define IDD_DIALOG2                     127
#define IDD_CFG_WATER                   128
#define IDD_CFG_COMMENT                 129
#define IDD_CFG_BRIGHTNESS              130
#define IDD_CFG_INTERLEAVE              131
#define IDD_CFG_GRAIN                   132
#define IDD_CFG_CLEAR                   133
#define IDD_CFG_BUMP                    134
#define IDD_CFG_MIRROR                  135
#define IDD_CFG_STARFIELD               136
#define IDD_CFG_TEXT                    137
#define IDD_BUMP_HELP                   138
#define IDD_CFG_MOSAIC                  139
#define IDD_CFG_WATERBUMP               140
#define IDR_MENU1                       140
#define IDD_CFG_AVI                     141
#define IDD_CFG_UNKN                    142
#define IDD_GCFG_TRANS                  143
#define IDD_CFG_BPM                     144
#define IDD_GCFG_BPM                    145
#define IDD_CFG_PICTURE                 146
#define IDD_CFG_DDM                     147
#define IDD_CFG_SSCOPE                  148
#define IDD_CFG_INVERT                  149
#define IDD_CFG_ONETONE                 150
#define IDD_CFG_TIMESCOPE               151
#define IDD_CFG_LIST                    152
#define IDD_CFG_LISTROOT                153
#define IDD_CFG_LINEMODE                154
#define IDD_GCFG_TRANSITIONS            155
#define IDD_GCFG_FS                     159
#define IDD_CFG_INTERF                  160
#define IDD_CFG_SHIFT                   161
#define IDD_CFG_DMOVE                   163
#define IDD_CFG_FASTBRIGHT              164
#define IDD_CFG_COLORMOD                165
#define IDD_EVAL_HELP                   166
#define IDD_DEBUG                       167
#define IDD_CFG_CHANSHIFT               168
#define IDD_CFG_COLORREDUCTION          169
#define IDD_CFG_MULT                    170
#define IDD_CFG_MULTIDELAY              171
#define IDD_CFG_VIDEODELAY              172
#define IDD_CFG_CONVOLUTION             173
#define IDD_CFG_TEXERII                 174
#define IDD_CFG_NORMALISE               175
#define IDD_CFG_COLORMAP                176
#define IDD_CFG_COLORMAP_COLOR_POSITION 177
#define IDD_CFG_ADDBORDERS              178
#define IDD_CFG_TRIANGLE                179
#define IDD_CFG_EELTRANS                180
#define IDD_CFG_EELTRANS_ERR            181
#define IDD_CFG_GLOBALVARS              182
#define IDD_CFG_MULTIFILTER             183
#define IDD_CFG_PICTUREII               184
#define IDD_CFG_FPSLIMITER              185
#define IDD_CFG_TEXER                   186
#define IDC_EFFECTS                     1000
#define IDC_ENABLED                     1001
#define IDC_FBCLEAR                     1002
#define IDC_DISSOC                      1003
#define IDC_DAMP                        1004
#define OBJ_COMBO                       1005
#define IDC_EFFECTRECT                  1006
#define IDC_BIN                         1007
#define IDC_RRECT                       1007
#define IDC_ADDITIVE                    1008
#define IDC_RADIUS                      1009
#define IDC_REMSEL                      1010
#define IDC_5050                        1011
#define IDC_LIB                         1012
#define IDC_DEFRENDBLEND                1012
#define IDC_REPLACE                     1013
#define IDC_RANDOM_DROP                 1014
#define IDC_ADD                         1015
#define IDC_LEVELS                      1015
#define IDC_DROP_LEFT                   1016
#define IDC_LEVELTEXT                   1016
#define IDC_ADAPT                       1017
#define IDC_MOVEUP                      1018
#define IDC_GBR                         1018
#define IDC_X8                          1018
#define IDC_RED                         1019
#define IDC_BRG                         1019
#define IDC_X4                          1019
#define IDC_HORIZONTAL1                 1020
#define IDC_RBG                         1020
#define IDC_DROP_CENTER                 1021
#define IDC_BGR                         1021
#define IDC_X05                         1021
#define IDC_PERSIST                     1022
#define IDC_GRB                         1022
#define IDC_X025                        1022
#define IDC_MOVEDOWN                    1023
#define IDC_X0125                       1023
#define IDC_GREEN                       1024
#define IDC_XI                          1024
#define IDC_HORIZONTAL2                 1025
#define IDC_XS                          1025
#define IDC_DROP_RIGHT                  1026
#define IDC_PERSIST_TITLE               1027
#define IDC_LOAD                        1028
#define IDC_LEFT                        1029
#define IDC_BLUE                        1030
#define IDC_X                           1031
#define IDC_MAX                         1032
#define IDC_X2                          1032
#define IDC_VERTICAL1                   1033
#define IDC_X3                          1033
#define IDC_DROP_TOP                    1034
#define IDC_SAVE                        1035
#define IDC_RIGHT                       1036
#define IDC_BRED                        1037
#define IDC_Y                           1038
#define IDC_VERTICAL2                   1039
#define IDC_Y2                          1039
#define IDC_DROP_MIDDLE                 1040
#define IDC_CLEAR                       1041
#define IDC_LC                          1042
#define IDC_BGREEN                      1043
#define IDC_LC2                         1043
#define IDC_DROP_BOTTOM                 1044
#define IDC_RC                          1045
#define IDC_CLONESEL                    1046
#define IDC_BBLUE                       1047
#define IDC_SPEED                       1048
#define IDC_DOTS                        1049
#define IDC_AVI_RESAMPLE                1050
#define IDC_DISTANCE                    1051
#define IDC_METHOD_SLUDGE               1052
#define IDC_PERSIST_TEXT1               1053
#define IDC_LINES                       1054
#define IDC_SLIDER1                     1055
#define IDC_EXCLUDE                     1056
#define IDC_SLIDER7                     1056
#define IDC_STAT                        1057
#define IDC_PERSIST_TEXT2               1058
#define IDC_LINES2                      1059
#define IDC_BLEND                       1060
#define IDC_SLIDER3                     1061
#define IDC_SMOOTH                      1062
#define IDC_BUTTON1                     1063
#define IDC_LINES3                      1064
#define IDC_BUTTON4                     1064
#define IDC_SLIDER4                     1065
#define IDC_SOLID                       1066
#define IDC_SLOWER                      1067
#define IDC_ONBEAT2                     1068
#define IDC_RATIO                       1069
#define IDC_SLIDER2                     1070
#define IDC_RSTACK_BLEND1               1070
#define IDC_X_RATIO                     1071
#define IDC_RSTACK_BLEND2               1071
#define IDC_CHECK1                      1072
#define IDC_RSTACK_BLEND3               1072
#define IDC_RSTACK_BLEND4               1073
#define IDC_BUTTON3                     1073
#define IDC_CHECK8                      1073
#define IDC_Y_RATIO                     1074
#define IDC_NEWADAPT                    1074
#define IDC_RSTACK_BLEND5               1074
#define IDC_C1                          1075
#define IDC_RSTACK_BLEND6               1075
#define IDC_INVERTDEPTH                 1075
#define IDC_SLIDER5                     1076
#define IDC_C2                          1076
#define IDC_RSTACK_BLEND7               1076
#define IDC_OFF                         1076
#define IDC_C3                          1077
#define IDC_RSTACK_BLEND8               1077
#define IDC_BANDS                       1077
#define IDC_C4                          1078
#define IDC_FPS                         1078
#define IDC_BANDTXT                     1078
#define IDC_RSTACK_BLEND9               1078
#define IDC_C5                          1079
#define IDC_SLIDER6                     1079
#define IDC_TREE1                       1079
#define IDC_RSTACK_BLEND10              1079
#define IDC_INSLIDE                     1080
#define IDC_RSTACK_BLEND11              1080
#define IDC_TRI                         1081
#define IDC_OUTSLIDE                    1081
#define IDC_ALPHASLIDE                  1081
#define IDC_RSTACK_BLEND12              1081
#define IDC_HLEFT                       1082
#define IDC_CBBUF2                      1082
#define IDC_BLENDSLIDE                  1082
#define IDC_CHECK6                      1083
#define IDC_CBBUF1                      1083
#define IDC_CHECK7                      1084
#define IDC_INVERT2                     1084
#define IDC_EFNAME                      1085
#define IDC_DEFAULTBLEND                1085
#define IDC_HCENTER                     1086
#define IDC_BPP_CONV                    1086
#define IDC_TRANSITION                  1087
#define IDC_WRAP                        1087
#define IDC_HRIGHT                      1088
#define IDC_EDIT1                       1089
#define IDC_VTOP                        1090
#define IDC_EDIT2                       1090
#define IDC_VCENTER                     1091
#define IDC_EDIT3                       1091
#define IDC_VBOTTOM                     1092
#define IDC_EDIT4                       1092
#define IDC_BKGND_RENDER                1092
#define IDC_COMBO1                      1093
#define IDC_SETDESKTOPCOLOR             1093
#define IDC_EDIT9                       1093
#define IDC_CHOOSEFONT                  1094
#define IDC_OVERLAYCOLOR                1094
#define IDC_EDIT66                      1094
#define IDC_T                           1095
#define IDC_COMBO2                      1095
#define IDC_DEFOVERLAYCOLOR             1095
#define IDC_EDIT7                       1095
#define IDC_EDIT                        1096
#define IDC_EDIT5                       1096
#define IDC_LEFTCH                      1097
#define IDC_EDIT6                       1097
#define IDC_BLANKS                      1098
#define IDC_NOMOVEMENT                  1098
#define IDC_EDIT10                      1098
#define IDC_RIGHTCH                     1099
#define IDC_USE_OVERLAY                 1099
#define IDC_EDIT11                      1099
#define IDC_RANDOMPOS                   1100
#define IDC_THREAD_PRIORITY             1100
#define IDC_EDIT12                      1100
#define IDC_MIDCH                       1101
#define IDC_EDIT13                      1101
#define IDC_OUTLINE                     1102
#define IDC_EDIT14                      1102
#define IDC_TOP                         1103
#define IDC_EDIT15                      1103
#define IDC_HSHIFT                      1104
#define IDC_FR1                         1104
#define IDC_EDIT16                      1104
#define IDC_CENTER                      1105
#define IDC_FR2                         1105
#define IDC_VSHIFT                      1106
#define IDC_BOTTOM                      1107
#define IDC_OUTLINESIZE                 1108
#define IDC_EDIT8                       1108
#define IDC_NUMCOL                      1109
#define IDC_RANDWORD                    1110
#define IDC_RADIO1                      1111
#define IDC_DEFOUTCOL                   1112
#define IDC_NEWRESET                    1112
#define IDC_BELOW                       1112
#define IDC_RADIO7                      1112
#define IDC_RADIO2                      1113
#define IDC_ABOVE                       1113
#define IDC_ANGLE                       1114
#define IDC_NEAR                        1114
#define IDC_HRESET                      1115
#define IDC_RADIO3                      1116
#define IDC_CHECK2                      1117
#define IDC_VRESET                      1118
#define IDC_CHECK9                      1118
#define IDC_RADIO4                      1119
#define IDC_PLAIN                       1120
#define IDC_RADIO5                      1121
#define IDC_SAVEFB                      1121
#define IDC_ROUNDDOWN                   1121
#define IDC_CHECK3                      1122
#define IDC_RESTFB                      1122
#define IDC_ROUNDUP                     1122
#define IDC_RADIO6                      1123
#define IDC_INVERT1                     1123
#define IDC_CHECK10                     1123
#define IDC_LIST1                       1124
#define IDC_CHECK11                     1124
#define IDC_CHECK5                      1125
#define IDC_CHECK4                      1126
#define IDC_SHADOW                      1127
#define IDC_CLEAR2                      1128
#define IDC_BUTTON2                     1129
#define IDC_VERSTR                      1130
#define IDC_OSC                         1131
#define IDC_SPEC                        1132
#define IDC_STATGRAIN                   1133
#define IDC_CLEARFIRSTFRAME             1134
#define IDC_DEPTH                       1135
#define IDC_SETTINGS                    1136
#define IDC_NUMSTARS                    1137
#define IDC_ONBEAT                      1138
#define IDC_SCROLLBAR1                  1139
#define IDC_SPDCHG                      1140
#define IDC_QUALITY2                    1141
#define IDC_TRANS_SLIDER                1142
#define IDC_DEPTH2                      1143
#define IDC_TRANS_CHECK                 1144
#define IDC_SPDDUR                      1145
#define IDC_AVS_VER                     1146
#define IDC_BEATDUR                     1147
#define IDC_DONT_MIN_AVS                1148
#define IDC_CODE1                       1149
#define IDC_BPMSTD                      1150
#define IDC_HELPBTN                     1151
#define IDC_BPMADV                      1152
#define IDC_CODE2                       1153
#define IDC_STICKY                      1154
#define IDC_CODE3                       1155
#define IDC_ONLYSTICKY                  1155
#define IDC_MOREADAPT                   1156
#define IDC_DOT                         1157
#define IDC_TEXT                        1158
#define IDC_WAVE                        1158
#define IDC_DEFCOL                      1159
#define IDC_QUALITY                     1160
#define IDC_BPM                         1161
#define IDC_CONFIDENCE                  1162
#define IDC_2X                          1163
#define IDC_DIV2                        1164
#define IDC_ARBVAL                      1165
#define IDC_RESET                       1166
#define IDC_SKIPVAL                     1167
#define IDC_STICK                       1167
#define IDC_INVERT                      1168
#define IDC_UNSTICK                     1168
#define IDC_ARBITRARY                   1169
#define IDC_ARBTXT                      1170
#define IDC_SKIPTXT                     1171
#define IDC_CURBPM                      1172
#define IDC_SKIPFIRST                   1172
#define IDC_CURCONF                     1173
#define IDC_SKIPFIRSTTXT                1173
#define IDC_SKIP                        1174
#define IDC_IN                          1175
#define IDC_OUT                         1176
#define IDC_NPOINTS                     1177
#define IDC_ROTATE                      1178
#define IDC_ALPHA                       1179
#define IDC_ROTATE2                     1180
#define IDC_DISTANCE2                   1181
#define IDC_ALPHA2                      1182
#define IDC_RGB                         1183
#define IDC_RGB2                        1184
#define IDC_INITROT                     1185
#define IDC_DEBUGREG_1                  1186
#define IDC_DEBUGREG_2                  1187
#define IDC_DEBUGREG_3                  1188
#define IDC_DEBUGREG_4                  1189
#define IDC_DEBUGREG_5                  1190
#define IDC_DEBUGREG_6                  1191
#define IDC_DEBUGREG_7                  1192
#define IDC_DEBUGREG_8                  1193
#define IDC_DEBUGREG_9                  1194
#define IDC_DEBUGREG_10                 1195
#define IDC_DEBUGREG_11                 1196
#define IDC_DEBUGREG_12                 1197
#define IDC_DEBUGREG_13                 1198
#define IDC_DEBUGREG_14                 1199
#define IDC_DEBUGREG_15                 1200
#define IDC_DEBUGREG_16                 1201
#define IDC_TAB1                        1203
#define IDC_LABEL1                      1204
#define IDC_STATIC_ALPHA                1205
#define IDC_STATIC_TRANS_TOTAL          1206
#define IDC_STATIC_TRANS_NONE           1207
#define IDC_THREADS                     1208
#define IDC_THREADSBORDER               1209
#define IDC_CONVOLUTION_CHECK1          1210
#define IDC_CONVOLUTION_EDIT1           1211
#define IDC_CONVOLUTION_EDIT2           1212
#define IDC_CONVOLUTION_EDIT3           1213
#define IDC_CONVOLUTION_EDIT4           1214
#define IDC_CONVOLUTION_EDIT5           1215
#define IDC_CONVOLUTION_EDIT6           1216
#define IDC_CONVOLUTION_EDIT7           1217
#define IDC_CONVOLUTION_EDIT8           1218
#define IDC_CONVOLUTION_EDIT9           1219
#define IDC_CONVOLUTION_EDIT10          1220
#define IDC_CONVOLUTION_EDIT11          1221
#define IDC_CONVOLUTION_EDIT12          1222
#define IDC_CONVOLUTION_EDIT13          1223
#define IDC_CONVOLUTION_EDIT14          1224
#define IDC_CONVOLUTION_EDIT15          1225
#define IDC_CONVOLUTION_EDIT16          1226
#define IDC_CONVOLUTION_EDIT17          1227
#define IDC_CONVOLUTION_EDIT18          1228
#define IDC_CONVOLUTION_EDIT19          1229
#define IDC_CONVOLUTION_EDIT20          1230
#define IDC_CONVOLUTION_EDIT21          1231
#define IDC_CONVOLUTION_EDIT22          1232
#define IDC_CONVOLUTION_EDIT23          1233
#define IDC_CONVOLUTION_EDIT24          1234
#define IDC_CONVOLUTION_EDIT25          1235
#define IDC_CONVOLUTION_EDIT26          1236
#define IDC_CONVOLUTION_EDIT27          1237
#define IDC_CONVOLUTION_EDIT28          1238
#define IDC_CONVOLUTION_EDIT29          1239
#define IDC_CONVOLUTION_EDIT30          1240
#define IDC_CONVOLUTION_EDIT31          1241
#define IDC_CONVOLUTION_EDIT32          1242
#define IDC_CONVOLUTION_EDIT33          1243
#define IDC_CONVOLUTION_EDIT34          1244
#define IDC_CONVOLUTION_EDIT35          1245
#define IDC_CONVOLUTION_EDIT36          1246
#define IDC_CONVOLUTION_EDIT37          1247
#define IDC_CONVOLUTION_EDIT38          1248
#define IDC_CONVOLUTION_EDIT39          1249
#define IDC_CONVOLUTION_EDIT40          1250
#define IDC_CONVOLUTION_EDIT41          1251
#define IDC_CONVOLUTION_EDIT42          1252
#define IDC_CONVOLUTION_EDIT43          1253
#define IDC_CONVOLUTION_EDIT44          1254
#define IDC_CONVOLUTION_EDIT45          1255
#define IDC_CONVOLUTION_EDIT46          1256
#define IDC_CONVOLUTION_EDIT47          1257
#define IDC_CONVOLUTION_EDIT48          1258
#define IDC_CONVOLUTION_EDIT49          1259
#define IDC_CONVOLUTION_EDIT50          1260
#define IDC_CONVOLUTION_EDIT51          1261
#define IDC_CONVOLUTION_EDIT52          1262
#define IDC_CONVOLUTION_EDIT53          1263
#define IDC_CONVOLUTION_CHECK2          1264
#define IDC_CONVOLUTION_CHECK3          1265
#define IDC_CONVOLUTION_CHECK4          1266
#define IDC_CONVOLUTION_BUTTON1         1267
#define IDC_CONVOLUTION_BUTTON2         1268
#define IDC_CONVOLUTION_BUTTON3         1269
#define IDC_CONVOLUTION_BUTTON4         1270
#define IDC_TEXERII_INIT                1271
#define IDC_TEXERII_FRAME               1272
#define IDC_TEXERII_BEAT                1273
#define IDC_TEXERII_POINT               1274
#define IDC_TEXERII_TEXTURE             1275
#define IDC_TEXERII_BILINEAR            1276
#define IDC_TEXERII_MASK                1277
#define IDC_TEXERII_RESIZE              1278
#define IDC_TEXERII_WRAP                1279
#define IDC_TEXERII_ABOUT               1280
#define IDC_TEXERII_EXAMPLE             1281
#define IDC_TEXERII_URL                 1282
#define IDC_NORMALISE_ENABLED           1283
#define IDC_COLORMAP_MAPVIEW            1284
#define IDC_COLORMAP_KEY_SELECT         1285
#define IDC_COLORMAP_OUT_BLENDMODE      1286
#define IDC_COLORMAP_FILENAME_VIEW      1287
#define IDC_COLORMAP_FILE_LOAD          1288
#define IDC_COLORMAP_FILE_SAVE          1289
#define IDC_COLORMAP_HELP               1290
#define IDC_COLORMAP_MAP_SELECT         1291
#define IDC_COLORMAP_MAP_ENABLE         1292
#define IDC_COLORMAP_ADJUSTABLE_SLIDER  1293
#define IDC_COLORMAP_MAP_CYCLING_SELECT 1294
#define IDC_COLORMAP_FLIP_MAP           1295
#define IDC_COLORMAP_CLEAR_MAP          1296
#define IDC_COLORMAP_NO_SKIP_FAST_BEATS 1297
#define IDC_COLORMAP_MAP_CYCLE_SPEED    1298
#define IDC_COLORMAP_CYCLE_INFO         1299
#define IDC_COLORMAP_COLOR_POSITION     1300
#define IDC_ADDBORDERS_ENABLE           1301
#define IDC_ADDBORDERS_COLOR            1302
#define IDC_ADDBORDERS_WIDTH            1303
#define IDC_TRIANGLE_INIT               1304
#define IDC_TRIANGLE_FRAME              1305
#define IDC_TRIANGLE_BEAT               1306
#define IDC_TRIANGLE_POINT              1307
#define IDC_EELTRANS_ENABLED            1308
#define IDC_EELTRANS_LOG_ENABLED        1309
#define IDC_EELTRANS_VERSION_PREFIX     1310
#define IDC_EELTRANS_VERSION            1311
#define IDC_EELTRANS_TRANSFIRST         1312
#define IDC_EELTRANS_READCOMMENTCODES   1313
#define IDC_EELTRANS_CODE               1314
#define IDC_EELTRANS_LOGPATH            1315
#define IDC_EELTRANS_NOTFIRST_MESSAGE   1316
#define IDC_GLOBALVARS_LOAD_ONCE        1317
#define IDC_GLOBALVARS_LOAD_FRAME       1318
#define IDC_GLOBALVARS_LOAD_CODE        1319
#define IDC_GLOBALVARS_LOAD_NONE        1320
#define IDC_GLOBALVARS_BOX_LOADSAVE     1321
#define IDC_GLOBALVARS_LABEL_LOADSAVE   1322
#define IDC_GLOBALVARS_FILEPATH         1323
#define IDC_GLOBALVARS_ENLARGE_INIT     1324
#define IDC_GLOBALVARS_CODE_INIT        1325
#define IDC_GLOBALVARS_ENLARGE_FRAME    1326
#define IDC_GLOBALVARS_CODE_FRAME       1327
#define IDC_GLOBALVARS_ENLARGE_BEAT     1328
#define IDC_GLOBALVARS_CODE_BEAT        1329
#define IDC_GLOBALVARS_CODE_LARGE       1330
#define IDC_GLOBALVARS_LABEL_REG_RANGE  1331
#define IDC_GLOBALVARS_REG_RANGE        1332
#define IDC_GLOBALVARS_LABEL_BUF_RANGE  1333
#define IDC_GLOBALVARS_BUF_RANGE        1334
#define IDC_GLOBALVARS_REG_RANGE_ERR    1335
#define IDC_GLOBALVARS_BUF_RANGE_ERR    1336
#define IDC_GLOBALVARS_SAVE_NOW         1337
#define IDC_GLOBALVARS_HELP             1338
#define IDC_MULTIFILTER_ENABLED         1339
#define IDC_MULTIFILTER_EFFECT          1340
#define IDC_MULTIFILTER_TOGGLEONBEAT    1341
#define IDC_PICTUREII_SOURCE            1342
#define IDC_PICTUREII_OUTPUT            1343
#define IDC_PICTUREII_ADJUSTABLE        1344
#define IDC_PICTUREII_BILINEAR          1345
#define IDC_PICTUREII_BEAT_OUTPUT       1346
#define IDC_PICTUREII_BEAT_ADJUSTABLE   1347
#define IDC_PICTUREII_BEAT_BILINEAR     1348
#define IDC_PICTUREII_URL               1349
#define IDC_PICTUREII_ERROR             1350
#define IDC_FPSLIMITER_ENABLED          1351
#define IDC_FPSLIMITER_FPS_SLIDER       1352
#define IDC_FPSLIMITER_FPS_LABEL        1353
#define IDC_TEXER_IMAGE                 1354
#define IDC_TEXER_INPUT_IGNORE          1355
#define IDC_TEXER_INPUT_REPLACE         1356
#define IDC_TEXER_OUTPUT_NORMAL         1357
#define IDC_TEXER_OUTPUT_MASKED         1358
#define IDC_TEXER_NUM_PARTICLES         1359
#define IDC_TEXER_NUM_PARTICLES_LABEL   1360
#define IDC_TEXER_ERROR                 1361
#define IDM_DISPLAY                     40001
#define IDM_PRESETS                     40002
#define IDM_TRANS                       40003
#define IDM_ABOUT                       40004
#define IDM_BPM                         40005
#define IDM_TRANSITIONS                 40006
#define IDM_FULLSCREEN                  40007
#define IDM_HELP_DEBUGWND               40008
#define IDM_UNDO                        40009
#define IDM_REDO                        40010
#define IDM_COLORMAP_MENU_ADD           40011
#define IDM_COLORMAP_MENU_EDIT          40012
#define IDM_COLORMAP_MENU_DELETE        40013
#define IDM_COLORMAP_MENU_SETPOS        40014

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 187
#define _APS_NEXT_COMMAND_VALUE  40015
#define _APS_NEXT_CONTROL_VALUE  1362
#define _APS_NEXT_SYMED_VALUE    101
#endif
#endif
