name: Build on Windows with MSVC

on:
- pull_request
- push

jobs:
  build_and_test:
    name: Build on Windows with MSVC
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1.3

      - uses: actions/checkout@v3

      - name: Configure
        shell: cmd
        run: |-
          md build
          cd build
          cmake -G"Visual Studio 17 2022" -A Win32 ..

      - name: Make
        run: msbuild "$env:GITHUB_WORKSPACE/build/vis_avs.sln" -m

      - name: Copy DLL
        shell: cmd
        run: copy build/Debug/vis_avs.dll vis_avs_281d_msvc_debug.dll

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: vis_avs_msvc
          path: vis_avs_281d_msvc_debug.dll
