name: Build on Ubuntu with MinGW GCC

on:
- pull_request
- push

jobs:
  check:
    name: Enforce clean clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install clang-format
        run: |-
          clang_major_version=19
          set -x -u -o pipefail
          source /etc/os-release
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${clang_major_version} main"
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends -V clang-format-${clang_major_version}
          echo "/usr/lib/llvm-${clang_major_version}/bin" >> "${GITHUB_PATH}"

      - name: Dump clang-format config
        run: |-
          clang-format -dump-config -style=file

      - name: Enforce clang-format clean
        run: |-
          clang_format_args=(
              -i
              -style=file
              -verbose
          )
          set -x -u -o pipefail
          shopt -s globstar  # Enable **/ for recursive globbing
          clang-format --version
          git ls-files '*.c' '*.cpp' '*.h' \
              | grep -vf <(grep -rl "^DisableFormat: *true" **/.clang-format \
                           | sed 's:/.clang-format::') \
              | xargs clang-format "${clang_format_args[@]}"
          git diff --exit-code  # i.e. fail CI on non-empty diff

  build-windows-on-linux:
    name: Build on Ubuntu with MinGW-GCC for Windows
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install build dependencies
        run: |-
          sudo apt update && sudo apt install --yes mingw-w64 libavformat-dev libavcodec-dev libswscale-dev

      - name: Configure
        run: |-
          set -e
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=CMake-MingWcross-toolchain.txt ..

      - name: Make
        run: |-
          make -C build VERBOSE=1
          find build
          mv build/vis_avs.dll build/vis_avs_281d_mingw_debug.dll

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: vis_avs_mingw
          path: build/*.dll

  build-windows-native:
    name: Build on Windows with MSVC for Windows
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce  # v2.0.0

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Configure
        shell: cmd
        run: |-
          md build
          cd build
          cmake -G"Visual Studio 17 2022" -A Win32 ..

      - name: Make
        run: msbuild "$env:GITHUB_WORKSPACE/build/vis_avs.sln" -m

      - name: Copy DLL
        shell: cmd
        run: copy build/Debug/vis_avs.dll vis_avs_281d_msvc_debug.dll

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: vis_avs_msvc
          path: vis_avs_281d_msvc_debug.dll

  build-linux-native:
    name: Build on Ubuntu with GCC for Linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install dependencies
        run: |-
          deps=(
            gcc-multilib
            g++-multilib
            libavformat-dev
            libavcodec-dev
            libswscale-dev
            libpipewire-0.3-dev
            autoconf gettext flex bison libtool autopoint  # for util-linux/libuuid
          )
          sudo apt update && sudo apt install --yes "${deps[@]}"
          .ci/tasks.sh build-libuuid-32bit install

      - name: Install Rust toolchain if rustup available
        run: |-
          if command -v rustup; then
            rustup target add i686-unknown-linux-gnu
          fi

      - name: Build
        run: |-
          .ci/tasks.sh build-linux32 verbose

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: libavs_linux
          path: |
            build_linux32/libavs.so
            build_linux32/avs
            build_linux32/avs-cli
